{% set data = load_setup_py_data() %}
{% set number = 0 %}

package:
  name: anaconda-anon-usage
  version: {{ data['version'] }}

source:
  path: ..

build:
  # Use a build number difference to ensure that the plugin
  # variant is slightly preferred by conda's solver.
  number: {{ number + 100 }}  # [variant=="plugin"]
  number: {{ number }}        # [variant=="patch"]
  string: py_{{ PKG_BUILDNUM }}
  noarch: python  # [not win]
  script_env:
   - NEED_SCRIPTS=no   # [variant=="plugin"]
   - NEED_SCRIPTS=yes  # [variant=="patch"]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
    - __unix  # [not win]
    - __win  # [win]
  run_constrained:
    - conda>=23.7  # [variant=="plugin"]
    - conda>=4.11,<23.7   # [variant=="patch"]

test:
  requires:
    - conda
    - pytest
    - pytest-cov
  source_files:
    - tests
  commands:
    - export ANACONDA_ANON_USAGE_DEBUG=1  # [unix]
    - export PYTHONUNBUFFERED=1  # [unix]
    - set ANACONDA_ANON_USAGE_DEBUG=1  # [win]
    - set PYTHONUNBUFFERED=1 # [win]
    - conda create -n testchild1 --yes
    - conda create -n testchild2 --yes
    - conda info
    - conda info --envs
    - python -m anaconda_anon_usage.install --status  # [variant=="patch"]
    - pytest -v tests/unit
    - python tests/integration/test_config.py

about:
  home: https://github.com/Anaconda-Platform/anaconda-anon-usage
  summary: basic anonymous telemetry for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
