{% set data = load_setup_py_data() %}
{% set number = 0 %}

package:
  name: anaconda-anon-usage
  version: {{ data['version'] }}

source:
  path: ..

build:
  # Use a build number difference to ensure that the plugin
  # variant is slightly preferred by conda's solver.
  number: {{ number + 100 }}  # [variant=="plugin"]
  number: {{ number }}        # [variant=="patch"]
  string: py_{{ PKG_BUILDNUM }}
  noarch: python
  script_env:
   - NEED_SCRIPTS=no   # [variant=="plugin"]
   - NEED_SCRIPTS=yes  # [variant=="patch"]

requirements:
  host:
    - python
    - setuptools
    - wheel
    - pip
  run:
    - python>=3.6
  run_constrained:
    - conda>=23.7  # [variant=="plugin"]
    - conda>=4.11,<23.7   # [variant=="patch"]

test:
  requires:
    - pip
    - conda
  imports:
    - anaconda_anon_usage
    - anaconda_anon_usage.patch
    - anaconda_anon_usage.tokens
  commands:
    - pip check
    - conda info | grep -q "user-agent.* aau/"

about:
  home: https://github.com/Anaconda-Platform/anaconda-anon-usage
  summary: basic anonymous telemetry for conda clients
  license: {{ data.get('license') }}
  license_file: LICENSE
